PROGRAM MAIN
	
	IMPLICIT NONE
	
	TYPE INPUT_DATA
		
		CHARACTER (264) :: NAME
		INTEGER         :: ID
		CHARACTER (264), DIMENSION(4) :: DIM_NAME
		INTEGER, DIMENSION(4) :: DIM_SIZE
		REAL, DIMENSION(:,:,:,:), ALLOCATABLE :: DATA_R
		
	END TYPE
	
	! Declare type
	TYPE(INPUT_DATA), DIMENSION(:), ALLOCATABLE :: L2VAR
	
	
	! Allocate 
	ALLOCATE( L2VAR(2) )
	
	! Test allocation
	ALLOCATE( L2VAR(1)%DATA_R(2,2,2,2) )
	ALLOCATE( L2VAR(2)%DATA_R(3,4,5,6) )
	
END PROGRAM